name: Vercel Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-cli: vercel
          vercel-token: ${{ secrets.DEPLOY_VERCEL_TOKEN }}
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.DEPLOY_VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.DEPLOY_VERCEL_PROJECT_ID }}
